import Head from 'next/head'
import React from 'react'
import Hero from '../../components/Layout/__About/Hero/Hero'

const AboutUs = () => {
  return (
    <>
      <Head>
        <title>Astroville</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero/>
      
    </>
  )
}

export default AboutUs
